### ISSUE TITLE
Issues with Redacted.ch

### ISSUE THREAD

**Issue by haweh** [pthcode/alexandria#8]
This script no longer works with redacted.ch as it's giving me this trace after editing my config file for auto uploading. 
Traceback (most recent call last):
  File "alexandria", line 518, in <module>
    if __name__ == '__main__': main()
  File "alexandria", line 511, in main
    trackers.append(tracker(username, password))
  File "alexandria", line 124, in __init__
    self.login(username, password)
  File "alexandria", line 211, in login
    self.authkey = doc.xpath('//*[@id="upload_table"]/div[1]/input[2]')[0].attrib['value']
IndexError: list index out of range

**Comment by Maxamus456** [comment]
I am also getting a very similar error
Traceback (most recent call last):
  File "alexandria", line 516, in <module>
    if __name__ == '__main__': main()
  File "alexandria", line 509, in main
    trackers.append(tracker(username, password))
  File "alexandria", line 124, in __init__
    self.login(username, password)
  File "alexandria", line 210, in login
    self.authkey = doc.xpath('//*[@id="upload_table"]/div[1]/input[2]')[0].attrib['value']
IndexError: list index out of range

**Comment by steamch** [comment]
same question

**Comment by Maxamus456** [comment]
@fostins I switched to this fork https://github.com/Aniverse/alexandria . It seems to work all you need to do it edit the .config file and switch pth to red. and maybe lower or remove the sleep time between scanning files
